spring:
  application:
    name: queue-batch

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  threads:
    virtual:
      enabled: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: validate           # batch는 스키마 안 건드림
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 500          # 배치 INSERT 크기 (CHUNK와 맞춤)
        order_inserts: true        # 같은 테이블 INSERT 모아 배치 효율↑

  data:
    redis:
      sentinel:
        master: mymaster

server:
  port: ${SERVER_PORT:8081}
